### ISSUE TITLE
Standalone app

### ISSUE THREAD

**Issue by hashrock** [kitsonk/kview#5]
Providing a standalone app might make it easier for users to get started. However, the binary size would probably become quite large.

**Comment by hashrock** [comment]
It seems that for now, it is not possible to create an executable file with 'deno compile' in Fresh pj.

https://github.com/denoland/fresh/issues/239

**Comment by kitsonk** [comment]
I suspect most people using kview would have Deno CLI installed for some purpose. I would rather try to make the ability to install/maintain kview as easy as possible.

**Comment by hashrock** [comment]
Yeah, I agree that installation from CLI is the easiest to maintain.
