### ISSUE TITLE
Installation fails with 500

### ISSUE THREAD

**Issue by jakewhelan** [kitsonk/kview#9]
The URL which the docs instruct you to use for installation returns 500:
https://kview.deno.dev/install

I was able to get it installed by cloning the repo, so I'm not blocked right now - thanks for creating kview!

![image](https://github.com/kitsonk/kview/assets/6076073/04039d2b-74cd-4c0d-85ee-70c2ae30dd78)

**Comment by kitsonk** [comment]
You don't navigate to the URL.  You run the URL via the [Deno runtime](https://deno.com/).

What happens when you run:

```
deno run -A -r https://kview.deno.dev/install
```

**Comment by jakewhelan** [comment]
I followed the instructions in the readme, it errors

**Comment by kitsonk** [comment]
> I followed the instructions in the readme, it errors

Could you provide the error your receive?

**Comment by kitsonk** [comment]
Ok, I found the problem, it appears a feature was added to a pre-release version of Fresh I was using and took advantage of, only to have it reverted (https://github.com/denoland/fresh/pull/2372) prior to release, which broke this.  I fixed this in 8b62fc50feacd09602337d51774eb443ff4e5f48.
